const src = {
  // pick imgs from the dom

  allImgs: [],
  allImgsDom: document.querySelectorAll(".main-window-imgs"),
  allVideosDom: document.querySelectorAll(".main-window-videos"),
  set() {
    this.allItems = {
      arrowRound: this.allImgsDom[0],
      blinkArrow: this.allImgsDom[1],
      laerrow: this.allImgsDom[2],
      laerrow2: this.allImgsDom[3],
      logo: this.allImgsDom[4],
      man: this.allImgsDom[5],
      measurearrow: this.allImgsDom[6],
      measurearrow2: this.allImgsDom[7],
      redsize: this.allImgsDom[8],
      speech_off_btn: this.allImgsDom[9],
      speech_on_btn: this.allImgsDom[10],
      talk_cloud: this.allImgsDom[11],
      iit_delhi_logo: this.allImgsDom[12],
      land: this.allImgsDom[13],
      chalk_with_hand: this.allImgsDom[14],
      chalk_markings5: this.allImgsDom[15],
      chalk_markings2: this.allImgsDom[16],
      chalk_markings6: this.allImgsDom[17],
      chalk_markings1: this.allImgsDom[18],
      chalk_markings3: this.allImgsDom[19],
      chalk_markings4: this.allImgsDom[20],
      marking_surface1: this.allImgsDom[21],
      marking_surface2: this.allImgsDom[22],
      marking_surface3: this.allImgsDom[23],
      marking_surface4: this.allImgsDom[24],
      marking_surface5: this.allImgsDom[25],
      marking_surface6: this.allImgsDom[26],
      anchor_plate: this.allImgsDom[27],
anchor_plate1: this.allImgsDom[28],
anchor_plate2: this.allImgsDom[29],
anchor_plate3: this.allImgsDom[30],
beam_3d_1: this.allImgsDom[31],
beam_3d_2: this.allImgsDom[32],
beam_3d_with_holes1: this.allImgsDom[33],
beam_3d_with_holes2: this.allImgsDom[34],
ct_prop1: this.allImgsDom[35],
ct_prop2: this.allImgsDom[36],
ct_prop3: this.allImgsDom[37],
ct_prop4: this.allImgsDom[38],
ct_prop5: this.allImgsDom[39],
ct_prop6: this.allImgsDom[40],
foot_adapter1: this.allImgsDom[41],
foot_adapter2: this.allImgsDom[42],
foot_adapter3: this.allImgsDom[43],
head_adapter1: this.allImgsDom[44],
head_adapter2: this.allImgsDom[45],
full_column: this.allImgsDom[46],
drill_machine: this.allImgsDom[47],
hammer: this.allImgsDom[48],
nail1: this.allImgsDom[49],
objective: this.allImgsDom[50],
real_foot_adapter: this.allImgsDom[51],
real_head_adapter: this.allImgsDom[52],
sheathing: this.allImgsDom[53],
sheathing1: this.allImgsDom[54],
sheathing2: this.allImgsDom[55],
sheathing3: this.allImgsDom[56],
sheathing4: this.allImgsDom[57],
steel_waler1: this.allImgsDom[58],
steel_waler2: this.allImgsDom[59],
steel_waler3: this.allImgsDom[60],
tie_rod1: this.allImgsDom[61],
tie_rod2: this.allImgsDom[62],
tie_rod3: this.allImgsDom[63],
tie_rod4: this.allImgsDom[64],
wing_nut_top1: this.allImgsDom[65],
wing_nut_top2: this.allImgsDom[66],
wing_nut_top3: this.allImgsDom[67],
wing_nut_top4: this.allImgsDom[68],
wing_nut_top5: this.allImgsDom[69],
wing_nut_full: this.allImgsDom[70],
beam_3d_with_one_hole: this.allImgsDom[71],
nail2: this.allImgsDom[72],
nail3: this.allImgsDom[73],
nail4: this.allImgsDom[74],
beam_3d_with_holes_nailing_helper: this.allImgsDom[75],
beam_3d_with_holes3: this.allImgsDom[76],
beam_3d_with_holes4: this.allImgsDom[77],
sheathing_full2: this.allImgsDom[78],
sheathing_full3: this.allImgsDom[79],
flange_claw1: this.allImgsDom[80],
flange_claw2: this.allImgsDom[81],
flange_claw3: this.allImgsDom[82],
flange_claw4: this.allImgsDom[83],
steel_waler_blue1: this.allImgsDom[84],
steel_waler_blue2: this.allImgsDom[85],
steel_waler_tilt1: this.allImgsDom[86],
steel_waler_tilt2: this.allImgsDom[87],
column_side1: this.allImgsDom[88],
column_front_side: this.allImgsDom[89],
column_back_side: this.allImgsDom[90],
column_left_side: this.allImgsDom[91],
column_right_side: this.allImgsDom[92],
column_sides_all: this.allImgsDom[93],
wing_nut_top6: this.allImgsDom[94],
wing_nut_top7: this.allImgsDom[95],
wing_nut_top8: this.allImgsDom[96],
drill_helper: this.allImgsDom[97],
      
      
      // * Videos
      // yoke_front_to_back: this.allVideosDom[0],
      // yoke_front_to_side: this.allVideosDom[1],
      // panel1: this.allVideosDom[2],
      // panel2: this.allVideosDom[3],
    };
  },
  allImgsInitialAxis: [],
  get(itemName) {
    return this.allItems[itemName];
  },
};
// setting src
src.set();
